# Generated by Django 4.2.7 on 2026-01-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, help_text='Public display name', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, help_text='Karma points'),
        ),
    ]
