# Generated by Django 4.2.7 on 2026-01-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City or Municipality', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
