# Generated by Django 5.2.10 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0004_user_city_user_province_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flagged_for_legal_action',
            field=models.BooleanField(default=False, help_text='Flagged by LGU for legal action due to trolling/misconduct'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_action_reason',
            field=models.TextField(blank=True, help_text='Reason for legal action'),
        ),
    ]
