# Generated by Django 4.2.7 on 2026-01-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0005_user_is_flagged_for_legal_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('LGU', 'LGU Staff'), ('ADMIN', 'System Admin')], default='USER', max_length=10),
        ),
    ]
