# Generated by Django 4.2.7 on 2026-01-27 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_management', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN', 'Banned User'), ('UNBAN', 'Unbanned User'), ('PROMOTE', 'Promoted Role'), ('DEMOTE', 'Demoted Role'), ('RESET_KARMA', 'Reset Karma'), ('DELETE_REPORT', 'Deleted Report'), ('ANNOUNCEMENT', 'Created Announcement')], max_length=20)),
                ('target', models.CharField(help_text='Username or Object ID', max_length=255)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('DANGER', 'Emergency/Danger'), ('SUCCESS', 'Success/Good News')], default='INFO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
