# Generated by Django 4.2.7 on 2026-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('PRIORITY_CHANGE', 'Priority Changed'), ('COMMENT', 'New Comment'), ('UPVOTE', 'Upvote Received'), ('DOWNVOTE', 'Downvote Received'), ('ASSIGNED', 'Concern Assigned'), ('RESOLVED', 'Concern Resolved'), ('ARCHIVED', 'Concern Archived')], default='STATUS_CHANGE', max_length=20),
        ),
    ]
