# Generated by Django 5.2.7 on 2025-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
