# Generated by Django 5.2.6 on 2025-10-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0002_concern_latitude_concern_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_concerns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concern',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concern',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
