# Generated by Django 5.2.9 on 2026-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Hide my identity from public view'),
        ),
    ]
