# Generated by Django 4.2.7 on 2026-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0005_concern_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='alias',
            field=models.CharField(blank=True, help_text='Display name if anonymous (optional)', max_length=50, null=True),
        ),
    ]
