# Generated by Django 4.2.7 on 2026-01-26 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concerns', '0006_concern_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_concerns', to=settings.AUTH_USER_MODEL),
        ),
    ]
