# Generated by Django 4.2.7 on 2026-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0007_alter_concern_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('POLICE', 'Police Station'), ('FIRE', 'Fire Station'), ('HOSPITAL', 'Hospital/Clinic'), ('BARANGAY', 'Barangay Hall'), ('EVACUATION', 'Evacuation Center')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
