# Generated by Django 4.2.7 on 2026-01-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0008_emergencyunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='concern',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
