# Generated by Django 4.2.7 on 2026-01-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0011_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='comment_author_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment_content_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot of comment content at time of report'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='concerns.comment'),
        ),
    ]
